// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvgkqnquqromecvkhzse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2Z2txbnF1cXJvbWVjdmtoenNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTQwNzgsImV4cCI6MjA3NDI3MDA3OH0.Jo41btMu2bh_DRaWrX7Md-MyaPUC7sdK4CnuUxVM1uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});